version: "3.9"

services:
  db:
    image: postgres:16
    container_name: err_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: err
      POSTGRES_PASSWORD: errpassword
      POSTGRES_DB: err_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
